//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketNumber { get; set; }
        public bool Discount { get; set; }
        public int SeatNumber { get; set; }
    
        public virtual Passage Passage { get; set; }
        public virtual Passanger Passanger { get; set; }
    }
}
