//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybill
    {
        public System.DateTime Date { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public int RouteNumber { get; set; }
        public string SNILS { get; set; }
        public string WaybillNumber { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Passage Passage { get; set; }
	}
}
